name: Rustup

description: Setup Rust with caching

inputs:
  # See https://rust-lang.github.io/rustup/concepts/components.html
  components:
    required: false
    type: string
    description: space separated Rust components, e.g. `clippy rustfmt rust-docs`

  tools:
    required: false
    type: string
    description: comma separated Cargo tools

  restore-cache:
    default: true
    required: false
    type: boolean
    description: whether to restore cache

  save-cache:
    default: false
    required: false
    type: boolean
    description: whether to save cache, e.g. `github.ref_name == 'main'`

  cache-key:
    default: 'main'
    required: false
    type: string
    description: cache key prefix

  cache-workspace-crates:
    default: false
    required: false
    description: "Similar to cache-all-crates. If `true` the workspace crates will be cached."

runs:
  using: composite
  steps:
    - name: Print Inputs
      shell: bash
      run: |
        echo 'components: ${INPUTS_COMPONENTS}'
        echo 'tools: ${INPUTS_TOOLS}'
        echo 'restore-cache: ${INPUTS_RESTORE_CACHE}'
        echo 'save-cache: ${INPUTS_SAVE_CACHE}'
        echo 'cache-key: ${INPUTS_CACHE_KEY}'
      env:
        INPUTS_COMPONENTS: ${{ inputs.components }}
        INPUTS_TOOLS: ${{ inputs.tools }}
        INPUTS_RESTORE_CACHE: ${{ inputs.restore-cache }}
        INPUTS_SAVE_CACHE: ${{ inputs.save-cache }}
        INPUTS_CACHE_KEY: ${{ inputs.cache-key }}

    - name: Change to minimal profile
      shell: bash
      run: |
        sed -i ${{ (runner.os == 'macOS' && '""') || '' }} -e 's/profile = "default"/profile = "minimal"/g' rust-toolchain.toml
        cat rust-toolchain.toml

    - name: Set Minimal Profile
      shell: bash
      run: rustup set profile minimal

    - name: Add Components
      shell: bash
      if: ${{ inputs.components }}
      run: rustup component add ${INPUTS_COMPONENTS}
      env:
        INPUTS_COMPONENTS: ${{ inputs.components }}

    - name: Install
      shell: bash
      run: |
        rustup show
        git restore . # restore rust-toolchain.toml change

    - name: Cache on ${{ github.ref_name }}
      uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2
      if: ${{ inputs.restore-cache == 'true' }}
      with:
        shared-key: ${{ inputs.cache-key }}
        save-if: ${{ inputs.save-cache == 'true' }}
        cache-workspace-crates: ${{ inputs.cache-workspace-crates }}

    - name: Install Tools
      uses: taiki-e/install-action@763e3324d4fd026c9bd284c504378585777a87d5 # v2.62.57
      if: ${{ inputs.tools }}
      with:
        tool: ${{ inputs.tools }}
